name: Ejecutar Pruebas Automatizadas

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium:latest
        ports:
          - 4723:4723
        options: >-
          --health-cmd="curl -f http://localhost:4723/status || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalar dependencias
      run: mvn install -DskipTests

    - name: Ejecutar pruebas
      run: mvn test
